// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAunsqXvwOj9Ghir5zaTLSgI-BQkPPpqQ4',
    appId: '1:103829537062:web:4b3281d32dfccc9a0e41e7',
    messagingSenderId: '103829537062',
    projectId: 'afia-plus-app-notify',
    authDomain: 'afia-plus-app-notify.firebaseapp.com',
    storageBucket: 'afia-plus-app-notify.firebasestorage.app',
    measurementId: 'G-EPCZVWKQPT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY6oLy9j7FsY4Wt9-sE74Rbo-SYf6el6c',
    appId: '1:103829537062:android:369f11c387e5f8c50e41e7',
    messagingSenderId: '103829537062',
    projectId: 'afia-plus-app-notify',
    storageBucket: 'afia-plus-app-notify.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi-Pa7gj1JBiAnooCbTdeF00FaBUWnzu8',
    appId: '1:103829537062:ios:587fcbfffc8796ec0e41e7',
    messagingSenderId: '103829537062',
    projectId: 'afia-plus-app-notify',
    storageBucket: 'afia-plus-app-notify.firebasestorage.app',
    iosBundleId: 'com.example.afiaPlusApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi-Pa7gj1JBiAnooCbTdeF00FaBUWnzu8',
    appId: '1:103829537062:ios:587fcbfffc8796ec0e41e7',
    messagingSenderId: '103829537062',
    projectId: 'afia-plus-app-notify',
    storageBucket: 'afia-plus-app-notify.firebasestorage.app',
    iosBundleId: 'com.example.afiaPlusApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAunsqXvwOj9Ghir5zaTLSgI-BQkPPpqQ4',
    appId: '1:103829537062:web:c7d4eb1936daf4e20e41e7',
    messagingSenderId: '103829537062',
    projectId: 'afia-plus-app-notify',
    authDomain: 'afia-plus-app-notify.firebaseapp.com',
    storageBucket: 'afia-plus-app-notify.firebasestorage.app',
    measurementId: 'G-B416GWY67B',
  );
}
